baseURL = "/"
languageCode = "en-us"
title = "jgray.dev"
theme="orglike"
copyright = "© jgray"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "UA-123"

paginate=5 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	featherIconsCDN=true

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jscottgray"

# Main menu Items

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2